let token=localStorage.getItem("tsukiraToken"),anime=[];
async function api(u,o={}){o.headers={...(o.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};let r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||"خطا");return d}
async function load(){anime=await api("/api/anime");document.getElementById("anime").innerHTML=anime.map(a=>`<article class="card"><img src="${a.image}" alt="${a.title}"><div><h3>${a.title}</h3><small>⭐ ${a.score} • ${a.year}</small><br><button onclick="setList(${a.id},'planned')">🔖 می‌خوام ببینم</button><button onclick="setList(${a.id},'watching')">▶ در حال تماشا</button><button onclick="setList(${a.id},'completed')">✓ تماشا شده</button><button onclick="rate(${a.id})">⭐ امتیاز</button><button onclick="comment(${a.id})">💬 کامنت</button></div></article>`).join("");loadLists();me()}
async function setList(id,status){if(!token)return alert("اول وارد شوید");await api("/api/me/lists",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({animeId:id,status})});loadLists()}
async function loadLists(){if(!token){lists.innerHTML="<div class='box'>برای ساخت کتابخانه شخصی وارد شوید.</div>";return}let l=await api("/api/me/lists");lists.innerHTML=l.length?l.map(x=>{let a=anime.find(a=>a.id===x.animeId);return `<div class="list"><b>${a?.title||"انیمه"}</b> — ${x.status}<button onclick="removeList(${x.animeId})">حذف</button></div>`}).join(""):"<div class='box'>کتابخانه خالی است.</div>"}
async function removeList(id){await api("/api/me/lists/"+id,{method:"DELETE"});loadLists()}
async function rate(id){if(!token)return alert("اول وارد شوید");let n=prompt("امتیاز از ۱ تا ۱۰؟");if(n)try{await api("/api/anime/"+id+"/rating",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating:Number(n)})});alert("ثبت شد ⭐")}catch(e){alert(e.message)}}
async function comment(id){if(!token)return alert("اول وارد شوید");let text=prompt("نظر شما؟");if(text)try{await api("/api/anime/"+id+"/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});alert("ثبت شد 💬")}catch(e){alert(e.message)}}
async function me(){if(!token)return;try{let u=await api("/api/me");mebox.innerHTML=`سلام ${u.name} 🌙<br><small>${u.email}</small><br><button onclick="logout()">خروج</button>`}catch(e){logout()}}
function logout(){localStorage.removeItem("tsukiraToken");location.reload()}
auth.onclick=async()=>{if(token){profile.scrollIntoView();return}let mode=prompt("login برای ورود یا register برای ثبت‌نام");if(!mode)return;let email=prompt("ایمیل؟"),password=prompt("رمز عبور حداقل ۶ کاراکتر؟"),body={email,password};if(mode==="register")body.name=prompt("نام نمایشی؟")||email.split("@")[0];try{let d=await api(mode==="register"?"/api/auth/register":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});localStorage.setItem("tsukiraToken",d.token);location.reload()}catch(e){alert(e.message)}};
const lists=document.getElementById("lists"),mebox=document.getElementById("me"),profile=document.getElementById("profile");load();